// scripts/sync-tags.js で自動生成 - 手動編集不要
// npm run sync-tags または npm run build で更新
export const KNOWN_TAGS = new Set([
  ' ',
  '/forum-jp',
  '/help-jp/',
  '/help-jp/サンプル',
  '/help-jp/ブラケティング',
  '/help/',
  '/nota-private-sample',
  '1】',
  'Air Plants Hub',
  'Avonia',
  'Cosense',
  'Davis Farm',
  'Ecuagenera',
  'JB_Orchids_Nursery',
  'Lepanthes',
  'Oc99',
  'Oxalis',
  'Rain_Forest_International',
  'Tilaria Plantae',
  'Tillandsia',
  'Tillandsia PROD',
  'Tillandsias Brasil',
  'WILD_WIND',
  'YAJIMA Succulents of Wild-Species',
  '`と` ',
  'avonia',
  'cape_bulb',
  'delta_memo',
  'flava種群',
  'irfa_garden',
  'lepanthes',
  'miniature_orchids',
  'minor phyto!',
  'mundi_flora',
  'oxalis',
  'south_america',
  'subg_diaphoranthema',
  'tillandsia',
  'torihada plants',
  'お問い合わせ https://cosen.se/contact',
  'つながり',
  'なべりんプランツ',
  'アルペンガーデンやまくさ',
  'カクタス長田',
  'サンシャインらん展',
  'タスク',
  'タナベフラワー',
  'ナミビア',
  'ハッシュタグ',
  'フラワーケンズ',
  'ブロメリアフェスタ',
  'ミニボタ',
  'メルカリ',
  'ヤフオク',
  'リンク',
  '中花柱花',
  '人物',
  '企業の利用事例を掲載しています https://cosen.se/case',
  '伊藤蟻植物農園',
  '別ページ',
  '大木ナーサリー',
  '当時Twitterで募集された共同輸入',
  '木立ち',
  '短花柱花',
  '自由',
  '草わるん',
  '蘭友会らん展',
  '読んだ本',
  '長花柱花',
]);
